# Generated by Django 4.2.9

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=50)),
                ('ssh_key', models.TextField(blank=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('zfs_pool', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(default='postgresql', max_length=50)),
                ('db_version', models.CharField(default='15', max_length=20)),
                ('container_name', models.CharField(max_length=100, unique=True)),
                ('zfs_dataset', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('username', models.CharField(default='postgres', max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hostvm')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('snapshot_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.database')),
            ],
            options={
                'unique_together': {('database', 'name')},
            },
        ),
    ]