# Generated by Django 4.2.9 on 2025-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='connection_string',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='database',
            name='container_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='database',
            name='container_status',
            field=models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('removing', 'Removing')], default='creating', max_length=20),
        ),
        migrations.AddField(
            model_name='database',
            name='database_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='database',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='database',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('starting', 'Starting'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='database',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='storage_quota_gb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='storage_used_mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
