# Generated by Django 4.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostvm',
            name='is_docker_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('warning', 'Warning'), ('invalid', 'Invalid'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='validation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='os_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='docker_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='docker_compose_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='zfs_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='zfs_pools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='system_resources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]