# Generated by Django 4.2.9 on 2025-08-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_database_management_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZFSOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', 'Create Dataset'), ('snapshot', 'Create Snapshot'), ('clone', 'Clone from Snapshot'), ('destroy', 'Destroy Dataset/Snapshot'), ('rollback', 'Rollback to Snapshot'), ('rename', 'Rename Dataset/Snapshot')], max_length=20)),
                ('source_dataset', models.CharField(blank=True, max_length=500)),
                ('target_dataset', models.CharField(blank=True, max_length=500)),
                ('snapshot_name', models.CharField(blank=True, max_length=200)),
                ('command_executed', models.TextField()),
                ('success', models.BooleanField()),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('operation_context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('host_vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hostvm')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='database',
            name='creation_type',
            field=models.CharField(choices=[('empty', 'Empty Dataset'), ('clone', 'Cloned from Database'), ('snapshot', 'Restored from Snapshot')], default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='database',
            name='source_database',
            field=models.ForeignKey(blank=True, help_text='Source database if this was cloned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.database'),
        ),
        migrations.AddField(
            model_name='database',
            name='source_snapshot',
            field=models.CharField(blank=True, help_text='Source snapshot name if restored from snapshot', max_length=200),
        ),
        migrations.DeleteModel(
            name='DatabaseBranch',
        ),
        migrations.AddField(
            model_name='zfsoperation',
            name='initiated_by_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.database'),
        ),
        migrations.AddField(
            model_name='database',
            name='created_from_operation',
            field=models.ForeignKey(blank=True, help_text="The ZFS operation that created this database's dataset", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zfsoperation'),
        ),
        migrations.AddIndex(
            model_name='zfsoperation',
            index=models.Index(fields=['operation_type', 'success'], name='core_zfsope_operati_4550f2_idx'),
        ),
        migrations.AddIndex(
            model_name='zfsoperation',
            index=models.Index(fields=['source_dataset'], name='core_zfsope_source__81b05f_idx'),
        ),
        migrations.AddIndex(
            model_name='zfsoperation',
            index=models.Index(fields=['target_dataset'], name='core_zfsope_target__010359_idx'),
        ),
        migrations.AddIndex(
            model_name='zfsoperation',
            index=models.Index(fields=['host_vm', '-started_at'], name='core_zfsope_host_vm_5eb306_idx'),
        ),
    ]
