# Generated by Django 4.2.9 on 2025-08-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_zfsoperation_database_creation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostvm',
            name='default_port_range',
            field=models.IntegerField(default=5432),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='default_username',
            field=models.CharField(blank=True, default='postgres', max_length=50),
        ),
        migrations.AddField(
            model_name='hostvm',
            name='user_accessible_host',
            field=models.CharField(blank=True, help_text='Hostname/IP that users will use to connect to databases (may differ from ip_address for SSH)', max_length=255),
        ),
    ]
