# Generated by Django 4.2.9 on 2025-08-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storageconfiguration_hostvm_storage_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageconfiguration',
            name='health_status',
            field=models.CharField(
                choices=[
                    ('healthy', 'Healthy'),
                    ('degraded', 'Degraded'),
                    ('failed', 'Failed'),
                    ('missing', 'Missing'),
                    ('unknown', 'Unknown')
                ],
                default='unknown',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='storageconfiguration',
            name='health_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storageconfiguration',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageconfiguration',
            name='last_reconciliation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageconfiguration',
            name='actual_pool_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storageconfiguration',
            name='sync_status',
            field=models.CharField(
                choices=[
                    ('synced', 'Synced'),
                    ('drift_detected', 'Drift Detected'),
                    ('out_of_sync', 'Out of Sync'),
                    ('unknown', 'Unknown')
                ],
                default='unknown',
                max_length=20
            ),
        ),
    ]